### ISSUE TITLE
Factorial of a number in c++ 

### ISSUE THREAD

**Issue by AmanPatre** [ghostmkg/programming-language#100]
Want to add a c++ code that calculates factorial of a given number.

please assign this to me .

**Comment by Arunendra21** [comment]
Hey , I got the algorithm. Kindly assign me this issue.

**Comment by ghostmkg** [comment]
@Arunendra21 and @AmanPatre Please raise the PR for this issue or I will close this issue

**Comment by ishwarthecodddr** [comment]
i have the code assign me this issue .

**Comment by AmanPatre** [comment]
Already added bro

**Comment by ishwarthecodddr** [comment]
then why not close the issue

**Comment by AmanPatre** [comment]
I dont know
