### ISSUE TITLE
Doubly Linked List CLI Program

### ISSUE THREAD

**Issue by AvinashK47** [ghostmkg/programming-language#119]
I would like to add Doubly Linked List CLI , so that users can understand how Doubly Linked List works.
Please assign me this issue so that i can work on this

**Comment by AvinashK47** [comment]
> I would like to add Doubly Linked List CLI , so that users can understand how Doubly Linked List works. Please assign me this issue so that i can work on this

Please assign me this under hacktoberfest and if possible also gssoc-ext

**Comment by AvinashK47** [comment]
@ghostmkg This is my first PR and it has been merged. Should I close this issue now, or will you handle it?

**Comment by ghostmkg** [comment]
Thank you for your contribution.
