### ISSUE TITLE
Java Program to create transpose of a square array

### ISSUE THREAD

**Issue by mahirabidi12** [ghostmkg/programming-language#127]
i would like to make contribution please assign this to me .

**Comment by mahirabidi12** [comment]
please assign this under hactoberfest tag

**Comment by mahirabidi12** [comment]
@ghostmkg  I have solved the given issue . Please merge it under hacktoberfest label.

**Comment by RekhaNPatil** [comment]
Hello , i would like solve the issue please assign it to me

**Comment by ghostmkg** [comment]
@RekhaNPatil It has been resolved but you can raise the PR for this issue again.

**Comment by RekhaNPatil** [comment]
Hello i raised the PR.

**Comment by ghostmkg** [comment]
Closing this issue
