### ISSUE TITLE
Python Program Pascal Triangle i

### ISSUE THREAD

**Issue by sayednowshad** [ghostmkg/programming-language#130]
i want to add the Pascal Triangle into it cause recent interviews they were asked for this in their placements i used to write in python

**Comment by sayednowshad** [comment]
please accept my issue to improve myself and help me out this thank for your Channel i am your new Subscriber

**Comment by ghostmkg** [comment]
@sayednowshad Please Raise this PR for this issue or I will close it.

**Comment by sayednowshad** [comment]
Accept my PR's & Merge It thank you
