### ISSUE TITLE
Javascript Bit manupulation.

### ISSUE THREAD

**Issue by PradeepFSTdhane123** [ghostmkg/programming-language#236]
Here, I want to contribute in javascript Bit manupulation problems.

Problem 1- Given a non-empty array of integers, every element appears twice except for one. Find that single one.

Problem 2: Given an integer n, return the number of 1 bits in its binary representation.

 @ghostmkg  "I am passionate about this project and would love to work on this issue. Could you please assign it to me? I am eager to start contributing and making a difference. Thank you for considering my request!"

**Comment by ghostmkg** [comment]
@PradeepFSTdhane123 Please Raise the PR or I will close this issue

**Comment by PradeepFSTdhane123** [comment]
@ghostmkg  Today I will raise the PR
