### ISSUE TITLE
Linear search algorithm

### ISSUE THREAD

**Issue by PradeepFSTdhane123** [ghostmkg/programming-language#290]
#  linear search algorithm  in java. 

@ghostmkg "I would love the opportunity to contribute and work on this project.
Could you please assign the issue to me? I'm eager to dive in and make a meaningful impact. Thank you for considering my request!".

**Comment by Aashana101** [comment]
@ghostmkg kindly assign this task to me. I would love to contribute to it. Thanking you in advance
