### ISSUE TITLE
Request to Contribute C++ Code Files for Hacktoberfest 2024

### ISSUE THREAD

**Issue by shash369** [ghostmkg/programming-language#31]
Hi,

I hope you're doing well. I am interested in contributing to the project by adding more C++ code files. I would greatly appreciate the opportunity to work on this and contribute to its development.

Could you kindly assign me this issue under Hacktoberfest 2024?

Thank you for your consideration.

**Comment by ghostmkg** [comment]
https://youtu.be/-KpH4fXBO3s?si=1xpDfQ8z6puIHAbP

Watch this video how to contribute.

**Comment by shash369** [comment]
done
