### ISSUE TITLE
feat: script to check internet speed

### ISSUE THREAD

**Issue by xXemran05khanXx** [ghostmkg/programming-language#5]

**Comment by xXemran05khanXx** [comment]
need permission

**Comment by xXemran05khanXx** [comment]
Assign me

**Comment by ghostmkg** [comment]
Please raise the PR if you are participating in Hacktober Fest

**Comment by xXemran05khanXx** [comment]
PS C:\Users\USER\OneDrive\Desktop\programming-language> git push origin Xxemran05khanxX        
remote: Permission to ghostmkg/programming-language.git denied to xXemran05khanXx.
fatal: unable to access 'https://github.com/ghostmkg/programming-language.git/': The requested URL returned error: 403

**Comment by ghostmkg** [comment]
https://youtu.be/-KpH4fXBO3s?si=sWaDe25wNdQnrIfk Watch this video on how to raise PR on this repo.

**Comment by xXemran05khanXx** [comment]
create a pr

**Comment by ghostmkg** [comment]
Closing the issue PR has been mearged.
