### ISSUE TITLE
Adding a 3sum program

### ISSUE THREAD

**Issue by vaibhav-gosavi** [ghostmkg/programming-language#88]
assign it to me and add a Hacktoberfest label to it

**Comment by mahirabidi12** [comment]
hey , i am mahir abidi . i would love to work on this so please assign this to me

**Comment by mahirabidi12** [comment]
Sir , i have submitted my changes please check it an merge it . and please use hacktoberfest tag as well.

**Comment by Arunendra21** [comment]
I got the solutions to this. Kindly assign me this issue.
