### ISSUE TITLE
Balanced_brackets.cpp 

### ISSUE THREAD

**Issue by TanishaBansal101** [ghostmkg/programming-language#91]
Balanced Brackets Checker (C++)
This C++ program checks if a given string of brackets is balanced or not. It uses a stack-based approach to ensure that each opening bracket has a corresponding closing bracket in the correct order.

Features:
Supports different types of brackets: (), {}, []
Efficiently checks for balance using a stack data structure
Handles edge cases like empty strings or invalid input
Example Input:
"[{()}]" → Balanced
"[{(}]" → Not Balanced
Usage:
The program can be used to verify if an expression with multiple types of brackets is syntactically correct, useful for parsing algorithms or coding challenges. 
Please assign me this task under HacktoberFest2024. Thank you!

**Comment by ghostmkg** [comment]
@TanishaBansal101 Please raise the PR for this. Or I will close this issue

**Comment by TanishaBansal101** [comment]
> @TanishaBansal101 Please raise the PR for this. Or I will close this issue

 @ghostmkg  I'll raise the PR shortly. Please keep the issue open until it's submitted.
